# Generated by Django 4.0.4 on 2022-05-07 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_rename_favourites_profile_my_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='my_favourites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='my_favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
