# Generated by Django 4.0.4 on 2022-05-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_prod',
            new_name='date_pod',
        ),
    ]
