# Generated by Django 4.0.4 on 2022-05-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_date_pob_product_date_pub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dete_pub',
            new_name='date_pub',
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product'),
        ),
    ]
