# Generated by Django 4.0.4 on 2022-04-25 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.user_product_image_path)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('date_prod', models.DateTimeField(auto_now_add=True)),
                ('date_creat', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favourites', models.ManyToManyField(blank=True, related_name='favourites_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
