# Generated by Django 4.0.4 on 2022-05-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_comment_dete_edit_alter_product_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_pod',
            new_name='date_pob',
        ),
    ]
