# Generated by Django 4.0.4 on 2022-05-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_favourites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscribers',
            new_name='subscriptions',
        ),
    ]
